- name: qemu-agent | install package
  tags: packages,qemu,qemu-agent
  package:
    state: latest
    name:
      - qemu-guest-agent
  notify:
    - restart_qemu_agent

- name: qemu-agent | enable qemu agent daemon
  tags: qemu,qemu-agent
  service:
    name: "{{ qemu_agent_service }}"
    enabled: yes
    state: started
