---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: /home/mocha/.tmux/plugins
    owner: mocha
    group: coffee
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: /home/mocha/.vim/bundle
    owner: mocha
    group: coffee
    recurse: true
