#- name: users | mocha | remove preinstalled clutter from home directory
#  file:
#    path: /home/mocha/{{ item }}
#    state: absent
#  with_items:
#    - examples.desktop
#    - Desktop
#    - Documents
#    - Downloads
#    - Music
#    - Pictures
#    - Public
#    - Templates
#    - Videos

- name: users | mocha | create personal config directories
  tags: dotfiles,dotfiles-jay
  file:
    path: /home/mocha/{{ item.dir }}
    state: directory
    owner: mocha
    group: mocha
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: templates }

- name: users | mocha | copy user-dirs.dirs
  tags: dotfiles,dotfiles-jay
  copy:
    src: users/mocha/user-dirs.dirs
    dest: /home/mocha/.config/user-dirs.dirs
    owner: mocha
    group: mocha
    mode: 0600
  notify: update_xdg

- name: users | mocha | copy personal config files
  tags: dotfiles,dotfiles-jay
  copy:
    src: users/mocha/{{ item.src }}
    dest: /home/mocha/{{ item.dest }}
    owner: mocha
    group: mocha
    mode: 0600
  with_items:
    - { src: 'asunder', dest: '.asunder' }
    - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
    - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
    - { src: 'gvimrc', dest: '.gvimrc' }
    - { src: 'linode-cli', dest: '.config/linode-cli' }
    - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

- name: users | mocha | copy profile image
  tags: dotfiles,dotfiles-jay
  copy:
    src: users/mocha/profile_image.png
    dest: /var/lib/AccountsService/icons/mocha.png
    owner: root
    group: root
    mode: 0644
