- name: Backup PVE config config.db + /etc 
  hosts: prox 
  become: yes
  tasks:
    - name: Mount NFS share
      ansible.builtin.mount:
        src: "{{ nfs_server }}:/export/Library"
        path: /mnt/Library
        fstype: nfs
        opts: rw,sync
        state: mounted
      vars:
        nfs_server: "192.168.1.110"  
    - name: Backup SQLite database
      ansible.builtin.command:
        cmd: sqlite3 /var/lib/pve-cluster/config.db ".backup '/mnt/Library/backup/proxmox/prox/config.db.{{ ansible_date_time.date }}'"
    - name: Create a tarball of /etc directory
      archive:
        path: /etc
        dest: /mnt/Library/backup/proxmox/prox/etc.tar.gz.{{ ansible_date_time.date }}
        format: gz
