- name: users | users | create group
  tags: groups,users
  group:
    name: users 
    gid: 100
    state: present

- name: users | family | create group
  tags: groups,family,users
  group:
    name: family
    gid: 1000 
    state: present

- name: users | Erika | create user
  tags: Erika,users
  user:
    name: Erika
    uid: 1001
    group: family
    groups: users 
    state: present
    password: "{{ Erika_passwd }}"
    shell: /bin/bash
