- name: users | users | create group
  tags: groups,users,users
  group:
    name: users 
    gid: 100
    state: present

- name: users | family | create group
  tags: groups,family,users
  group:
    name: family
    gid: 1000 
    state: present

- name: users | Zsolti | create user
  tags: Zsolti,users
  user:
    name: Zsolti
    uid: 1000
    group: family,users 
    state: present
    password: "{{ Zsolti_passwd }}"
    shell: /bin/bash
