- name: notify healthchecks.io that the job ran
  uri:
    url: https://hc-ping.com/{{ healthcheck_uuid }}
  changed_when: False
  when: healthcheck_uuid is defined

- name: send completion notification via telegram
  tags: always
  telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      msg_format: markdown
      parse_mode: markdown
      text: "✔️  Ansible provision finished on *{{ ansible_hostname }}*"
  changed_when: False
